# Generated by Django 5.1 on 2024-08-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorruptionStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Enter amount')),
                ('banner', models.ImageField(help_text='Upload the banner image', upload_to='')),
                ('content', models.TextField(help_text='Enter article body')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('headline', models.CharField(help_text='Enter the article headline', max_length=300)),
                ('is_published', models.BooleanField(default=False, help_text='Is published?')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
