# Generated by Django 5.1 on 2024-09-04 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corruptionstory',
            name='date_published',
        ),
        migrations.AddField(
            model_name='corruptionstory',
            name='date_occured',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Enter the date the corruption occured'),
            preserve_default=False,
        ),
    ]
