# Generated by Django 5.1 on 2024-09-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_corruptionstory_date_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corruptionstory',
            options={'ordering': ['-date_occured']},
        ),
    ]
